# Generated by Django 4.1.7 on 2023-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=300)),
                ('person_email', models.EmailField(max_length=300)),
                ('person_dob_time', models.DateTimeField()),
                ('person_state', models.CharField(max_length=200)),
                ('person_gender', models.CharField(max_length=200)),
                ('person_location', models.CharField(max_length=300)),
                ('person_image', models.ImageField(blank=True, upload_to='image')),
                ('person_document', models.FileField(blank=True, upload_to='document')),
            ],
        ),
    ]
